### ISSUE TITLE
Q: protect any sub-content?

### ISSUE THREAD

**Issue by RickCogley** [reverentgeek/jamstack-hugo-demo#1]
Hi - does the login protection extend to any pages you make under `content` ?

That is, if I'm not logged in, but try to access `/post/jamstack/` in the deployed site, will it redirect to login before granting access?

**Comment by reverentgeek** [comment]
Hi Rick,

Anything based on JavaScript will run *after* the page loads. If the sensitive content exists on the page, it can still be crawled by search engines or accessed by disabling JavaScript in the client so the redirect to login doesn't happen.

My recommendation would be to store any sensitive content behind an API and dynamically fetch it using a JWT when the page loads.

I hope this helps!
